# Generated by Django 5.1.3 on 2024-12-11 09:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('labour_management', '0001_initial'),
        ('masters', '0008_alter_laborskill_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('land_facing', models.CharField(max_length=100)),
                ('land_width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('land_breadth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_floors', models.IntegerField()),
                ('build_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_status', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='project_documents/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='masters.documenttype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='LaborToProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='labour_management.labormanagement')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_assignments', to='project.project')),
            ],
            options={
                'unique_together': {('labor', 'project')},
            },
        ),
    ]
