# Generated by Django 5.1.3 on 2024-12-11 11:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='labortoproject',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='LaborTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('ADV', 'Advance'), ('PAY', 'Payment'), ('WORK', 'Work Entry')], max_length=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('labor_to_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='project.labortoproject')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_type', models.CharField(choices=[('HALF', 'Half-Day'), ('FULL', 'Full-Day'), ('OT', 'Overtime')], default='FULL', max_length=4)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('labor_to_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_days', to='project.labortoproject')),
            ],
        ),
        migrations.RemoveField(
            model_name='labortoproject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='labortoproject',
            name='updated_at',
        ),
    ]
