# Generated by Django 5.1.3 on 2024-12-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labour_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labormanagement',
            name='document_type',
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
    ]
