# Generated by Django 5.1.3 on 2024-12-08 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour_management', '0001_initial'),
        ('masters', '0006_laborskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labormanagement',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.laborskill'),
        ),
    ]
