# Generated by Django 5.1.4 on 2024-12-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeType',
        ),
    ]
