# Generated by Django 5.1.3 on 2024-12-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_alter_documenttype_name_alter_employeetype_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborskill',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
