# Generated by Django 5.1.4 on 2024-12-21 08:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour_management', '0001_initial'),
        ('project', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='labormanagement',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='AdHocEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hired_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_assignments', to='labour_management.labormanagement')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_employees', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='LaborTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('ADV', 'Advance'), ('PAY', 'Payment')], max_length=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('labor_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='labour_management.labormanagement')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_type', models.CharField(choices=[('HALF', 'Half-Day'), ('FULL', 'Full-Day'), ('OT', 'Overtime')], default='FULL', max_length=4)),
                ('adhoc_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_days', to='labour_management.adhocemployee')),
            ],
        ),
    ]
