# Generated by Django 5.1.4 on 2024-12-21 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour_management', '0002_labormanagement_salary_adhocemployee_and_more'),
        ('project', '0003_labortoproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='labor_to_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_days', to='project.labortoproject'),
        ),
        migrations.AddConstraint(
            model_name='labortransaction',
            constraint=models.UniqueConstraint(fields=('labor_management', 'date', 'transaction_type'), name='unique_labor_transaction'),
        ),
    ]
